export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const TICKETS_REQUEST = 'TICKETS_REQUEST';
export const TICKETS_SUCCESS = 'TICKETS_SUCCESS';
export const TICKETS_FAILURE = 'TICKETS_FAILURE';

export const TODO_EDIT = 'TODO_EDIT';
export const TODOS_ADD = 'TODOS_ADD';
export const TODO_ADD = 'TODO_ADD';
export const TODOS_DELETE = 'TODO_DELETE';


